---
title: "gm methods_revised"
author: 
date: 
output:
  word_document:
    reference_docx: manuscriptstyle.docx
csl: new-phytologist.csl
bibliography: references.bib
---

```{r, results='asis', echo=FALSE, warning=FALSE}
library(knitr)
opts_knit$set(root.dir = '../')
```


Synchronized gas exchange and C isotope discrimination measurements were made similarly as described in Tazoe et al. [-@tazoe2011using] and Evans & von Caemmerer [-@evans2013temperature]. Leaf level gas exchange was measured with a standard (2 x 3 cm) leaf cuvette using a portable gas exchange system (LI-6400XT, LI-COR, Lincoln, NE, USA). This system was coupled with a tunable diode laser (TDL; TGA100,Campbell Scientific, Inc., Logan, UT, USA) for concurrent measurements of online C isotope discrimination. The CO~2~ in the leaf cuvette was set at ambient atmospheric [CO~2~] (400 ppm) with a flow rate of 200 $\mu$mol s^-1^. Two identical gas exchanges systems were run simultaneously, one in each of a randomly chosen WTC for each temperature treatment. Leaf temperatures were controlled at the current AT or ET WTC air temperature. PPFD in the cuvette was set to match the individual light environment of each leaf type (explained above). Periods of high irradiance were simulated for shade leaves by increasing the leaf cuvette PPFD (LI-COR red/blue light source) to match the light environment of the full sun leaf in the same tree. The maximum sunfleck response of shade leaves was then recorded once CO~2~ and water vapour fluxes re-stabilized in the leaf cuvette (ca. 25 min). 

\
Once CO~2~ and water vapour flux values were stable for each leaf measurement, the sample and reference gas lines were diverted to the TDL via T-junctions inserted into the reference gas tube and match valve outlet of the LI-6400XT. The gas streams were dried by passing through napion gas dryers in the respective gas lines, and then ^12^CO~2~ and ^13^CO~2~ concentrations were measured for each gas stream by the TDL. Reference, sample and two calibration gases were run on alternating 80 s loops (20 s each), one for each AT and ET leaf at a matched canopy position, for a total of 12 min. This allowed for 4-5 measurements per leaf and data were averaged over the last 10 s of reference line and samples line gas streams for calculations. The two calibration gases were drawn from compressed air tanks (330 and 740 ppm CO~2~) in order to correct for gain drift of the TDL on each measurement cycle. Photosynthesis, g~s~, transpiration, VPD and intercellular [CO~2~] (C~i~) were auto-logged every 15 s for each gas exchange system over the 12 min interval. 

\
Mesophyll conductance was calculated from carbon isotope discrimination with equations and fractionation factors as presented in Evans & von Caemmerer (2013), including the ternary corrections proposed by Farquhar & Cernusak (2012), such that:

\
(1)
$$\Delta_o = \Delta_i - \Delta_{gm} - \Delta_e - \Delta_f$$

where $\Delta$~o~ is the observed discrimination and $\Delta$~i~, $\Delta$~gm~ , $\Delta$~e~ and $\Delta$~f~ are the contributions to fractionation if C~i~ = C~c~, g~m~, respiration and photorespiration, respectively. For this study, the CO~2~ compensation point ($\Gamma_{*}$) and respiration during the day (R~d~) parameters originally derived for tobacco plants [@von1994kinetics] were replaced with parameters derived for *Eucalyptus globulus* from Crous et al. [-@crous2012light] when calculating g~m~. The variation in $\Delta$~o~ between sun and shade leaves and the simulated sunfleck where compared as a function of C~i~:C~a~. Once g~m~ was caluclated the chloroplast CO~2~ partial pressure (C~c~) and the drawdown of CO~2~ from the intercellular air spaces to the site of carboxylation were able to be estimated from the relationship between g~m~ to the leaf photosynthesis rate (*A~n~*) by:

\
(2)
$$g_m = \frac{*A~n~*}{C_i-C_c}$$


 


 
 
